version: '3.9'

services:
  app:
    build: ./backend
    container_name: fastapi_app
    volumes:
      - ./backend:/app  # Mount the code directory
    working_dir: /app
    ports:
      - "8000:8000"  # Expose FastAPI port
    environment:
      MONGO_URI: "mongodb://masteruser:securepassword123@host.docker.internal:27017/?directConnection=true&tls=true&tlsAllowInvalidHostnames=true&tlsCAFile=/app/global-bundle.pem&retryWrites=false"
    networks:
      - app_network
    restart: always
      
networks:
  app_network:
    driver: bridge
