version: '3.9'

services:
  app:
    image: python:3.10
    container_name: fastapi_app
    volumes:
      - ./backend:/app  # Mount the code directory
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"  # Expose FastAPI port
    environment:
      MONGO_URI: "mongodb://masteruser:securepassword123@host.docker.internal:27017/?directConnection=true&tls=true&tlsAllowInvalidHostnames=true&tlsCAFile=/app/global-bundle.pem&retryWrites=false"
    depends_on:
      - ssh-tunnel
    networks:
      - app_network

  ssh-tunnel:
    image: alpine:latest
    container_name: ssh_tunnel
    command: >
      sh -c "apk add --no-cache openssh &&
      ssh -T -o StrictHostKeyChecking=no -i /ssh-key/BastionForDocDb.pem -L 27017:10.0.102.175:27017 ubuntu@3.226.249.25 -N"
    volumes:
      - ./backend:/ssh-key  # Mount the SSH key directory
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
